//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibWarehouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СкладскойУчетEntities : DbContext
    {
        public СкладскойУчетEntities()
            : base("name=СкладскойУчетEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Инвентаризация> Инвентаризация { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Остатки_На_Складе> Остатки_На_Складе { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Приходные_Накладные> Приходные_Накладные { get; set; }
        public virtual DbSet<Расходные_Накладные> Расходные_Накладные { get; set; }
        public virtual DbSet<Склады> Склады { get; set; }
        public virtual DbSet<Строки_Инвентаризации> Строки_Инвентаризации { get; set; }
        public virtual DbSet<Строки_Приходных_Накладных> Строки_Приходных_Накладных { get; set; }
        public virtual DbSet<Строки_Расходных_Накладных> Строки_Расходных_Накладных { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
