//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инвентаризация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Инвентаризация()
        {
            this.Строки_Инвентаризации = new HashSet<Строки_Инвентаризации>();
        }
    
        public int ID_Инвентаризации { get; set; }
        public System.DateTime Дата_Проведения { get; set; }
        public int Ответственный { get; set; }
        public string Результаты { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строки_Инвентаризации> Строки_Инвентаризации { get; set; }
    }
}
