//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Остатки_На_Складе
    {
        public int ID_Остатка { get; set; }
        public int ID_Товара { get; set; }
        public int ID_Склада { get; set; }
        public int Текущее_Количество { get; set; }
    
        public virtual Склады Склады { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
