//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расходные_Накладные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Расходные_Накладные()
        {
            this.Строки_Расходных_Накладных = new HashSet<Строки_Расходных_Накладных>();
        }
    
        public int ID_Расходной_Накладной { get; set; }
        public string Номер_Накладной { get; set; }
        public System.DateTime Дата_Отгрузки { get; set; }
        public int ID_Клиента { get; set; }
        public decimal Общая_Сумма { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строки_Расходных_Накладных> Строки_Расходных_Накладных { get; set; }
    }
}
