//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Остатки_На_Складе = new HashSet<Остатки_На_Складе>();
            this.Строки_Инвентаризации = new HashSet<Строки_Инвентаризации>();
            this.Строки_Приходных_Накладных = new HashSet<Строки_Приходных_Накладных>();
            this.Строки_Расходных_Накладных = new HashSet<Строки_Расходных_Накладных>();
        }
    
        public int ID_Товара { get; set; }
        public string Название { get; set; }
        public string Артикул { get; set; }
        public string Штрихкод { get; set; }
        public string Категория { get; set; }
        public string Единица_измерения { get; set; }
        public decimal Цена_за_единицу { get; set; }
        public string Серийный_номер { get; set; }
        public int Минимальный_остаток { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Остатки_На_Складе> Остатки_На_Складе { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строки_Инвентаризации> Строки_Инвентаризации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строки_Приходных_Накладных> Строки_Приходных_Накладных { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строки_Расходных_Накладных> Строки_Расходных_Накладных { get; set; }
    }
}
