//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WerehouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приходные_Накладные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Приходные_Накладные()
        {
            this.Строки_Приходных_Накладных = new HashSet<Строки_Приходных_Накладных>();
        }
    
        public int ID_Приходной_Накладной { get; set; }
        public string Номер_Накладной { get; set; }
        public System.DateTime Дата_Поступления { get; set; }
        public int ID_Поставщика { get; set; }
        public decimal Общая_Сумма { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строки_Приходных_Накладных> Строки_Приходных_Накладных { get; set; }
    }
}
