//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WerehouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склады
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Склады()
        {
            this.Остатки_На_Складе = new HashSet<Остатки_На_Складе>();
        }
    
        public int ID_Склада { get; set; }
        public string Название_Склада { get; set; }
        public string Адрес { get; set; }
        public string Тип_Склада { get; set; }
        public string Зона_Хранения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Остатки_На_Складе> Остатки_На_Складе { get; set; }
    }
}
